### PR TITLE
purged unused sound array parts

### PR DESCRIPTION
**Pull request by N6REJ**

### CODE REVIEW

**Comment by N6REJ** [comment]
#21

**Review by N6REJ — COMMENTED** [review]
@Vae2009 somehow I got this mixed into the other sound pr.

**Review by Vae2009 — APPROVED** [review]
I see the cleanup here. Looks solid.

**Comment by Vae2009** [comment]
I'm going to test the debuff sound more first. I'm not sure the "player" code should be removed, yet.

**Comment by N6REJ** [comment]
sounds good.. merge when/if your ready.

**Comment by N6REJ** [comment]
Actually you might be right.

**Comment by N6REJ** [comment]
@Vae2009 you get a chance to make a decision on this?

**Comment by Vae2009** [comment]
Ya, the player code needs to stay in. Just not sure How to "undo" or whatnot.

**Review by Vae2009 — CHANGES_REQUESTED** [review]
Change back

**Comment by N6REJ** [comment]
@Vae2009 done.

**Review by Vae2009 — APPROVED** [review]

**Pull request merged**
